### ISSUE TITLE
Better memcpy

### ISSUE THREAD

**Issue by mmozeiko** [michal-z/eneida#1]
There is really no need to put memset in external asm file. You can put implementation in C file.
For example, here's one way how to implement it:

    #pragma function(memset)
    void *memset(void *dest, int c, size_t count)
    {
        __stosb((unsigned char*)dest, (unsigned char)c, count);
        return dest;
    }

This will simply generate "rep stosb" x86 instruction.
Similarly you can do memcpy with __movsb intrinsic.

**Comment by michal-z** [comment]
Unfortunately this solution won't work with whole-program optimization (/LTCG). See here: https://stackoverflow.com/a/2945619

**Comment by michal-z** [comment]
Well, actually it works in VS 2017 compiler. Thanks.

**Comment by michal-z** [comment]
It turned out that it doesn't work with /GL /LTCG (whole-program optimization). There is an compiler error. So, going with asm is the only way I know that work in every case.

**Comment by mmozeiko** [comment]
Well you can always put this function in separate translation unit and compile it without /GL. That's pretty much what you are doing now anyways, except writing raw assembly instead of C.

There's also no need for sqrtf in assembly. It's much faster to do _mm_sqrt_ss in C (include intrin.h header). Because that can be inlined & optimized instead of calling external function.

**Comment by michal-z** [comment]
sqrtf function is called only in Debug mode. In Release (/Ox, /Oi, /fp:fast) compiler generates sqrtss so this is fine. I'm not using any external headers so I can't include intinsics header. I could declare it but I prefer my solution because I can issue an assert in my assembly sqrtf function (to catch invalid params in Debug).

**Comment by mmozeiko** [comment]
That is not guaranteed - compiler can decide to leave call to sqrtf function if he wants, for whatever reason... Using intrinsic will gurantee generation of sqrtss instruction, no external function call.

If you want assert, then simply create your own function:

    float mysqrt(float x) { 
      ... assert checks ...
      ... use _mm_sqrt_ss here ...
    }

**Comment by michal-z** [comment]
Yes, I know that this is not guaranteed but it always worked for me in case of sqrt and cl compiler. I don't want to mess with intrinsics for now (I would have to introduce __m128 type and manually declare intrinsics). I want to keep it very simple in this project.
